server:
  port: 8762

spring:
  application:
    name: service-alarm-record
# mysql config     
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/device?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: root 
    password: 1518290
  zipkin:
    base-url: http://localhost:9412

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.129.133:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        