server:
  port: 8764

spring:
  application:
    name: service-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

turbine:
  app-config: service-alarm-record,service-feign
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
